# core/code_generator.py
from datetime import datetime
from core.block_data_models import BlockProject, FunctionBlockData

def generate_arduino_code(project: BlockProject) -> str:
    """
    Генерирует Arduino C++ код на основе данных проекта блоков.
    """
    code_parts = []

    # Заголовок
    code_parts.append("// Generated by Arduino Block Editor")
    code_parts.append(f"// Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    code_parts.append("\n")

    # Глобальные переменные (если будут)
    # code_parts.append("// Global variables here\n")

    global_block_content = ""
    setup_block_content = ""
    loop_block_content = ""
    function_blocks_content = []

    # Пользовательские функции
    for block in project.function_blocks:
        if block.block_type == "global":
            global_block_content = block.code_content
        elif block.block_type == "setup":
            setup_block_content = block.code_content
        elif block.block_type == "loop":
            loop_block_content = block.code_content
        else: # Обычные функции
            function_blocks_content.append(f"// --- Function: {block.name} ---")
            if block.description:
                function_blocks_content.append(f"// Description: {block.description}")
            
            # Интеллектуальное формирование сигнатуры функции
            signature = block.name.strip()
            
            # 1. Если скобки отсутствуют, добавляем пустые скобки ()
            if "(" not in signature:
                signature += "()"
            
            # 2. Если в части до скобок нет пробела, значит тип возвращаемого значения (void, int и т.д.) не указан
            # Мы берем часть до первой скобки и проверяем наличие в ней пробела
            if " " not in signature.split("(")[0].strip():
                signature = "void " + signature
                
            function_blocks_content.append(f"{signature} {{\n{block.code_content}\n}}\n")

    # Добавляем глобальный блок в начало
    if global_block_content:
        code_parts.append("// --- Global Includes & Variables ---")
        code_parts.append(global_block_content)
        code_parts.append("\n")

    # Добавляем пользовательские функции
    code_parts.extend(function_blocks_content)
    code_parts.append("\n")

    # Добавляем setup()
    code_parts.append("// --- Arduino Setup Function ---")
    code_parts.append(f"void setup() {{\n{setup_block_content}\n}}\n")

    # Добавляем loop()
    code_parts.append("// --- Arduino Loop Function ---")
    code_parts.append(f"void loop() {{\n{loop_block_content}\n}}\n")

    return "\n".join(code_parts)
